apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: medical-inventory
spec:
  template:
    spec:
      containers:
      - name: api
        env:
        - name: ENV
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: METRICS_ENABLED
          value: "true"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: production-secrets
              key: SENTRY_DSN
              optional: true
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 3
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3