apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gpu
  namespace: medical-inventory
  labels:
    app.kubernetes.io/name: api-gpu
    app.kubernetes.io/component: backend-gpu
    app.kubernetes.io/part-of: medical-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gpu
      app.kubernetes.io/component: backend-gpu
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-gpu
        app.kubernetes.io/component: backend-gpu
        app.kubernetes.io/part-of: medical-inventory
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
      - name: registry-secret
      nodeSelector:
        accelerator: nvidia-tesla-gpu
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - name: api-gpu
        image: medical-inventory:gpu-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: medical-inventory-config
              key: REDIS_URL
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: medical-inventory-secrets
              key: DATABASE_URL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: medical-inventory-config
              key: LOG_LEVEL
        - name: MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: medical-inventory-config
              key: MODEL_PATH
        - name: WORKERS
          value: "2"  # Fewer workers for GPU deployment
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: medical-inventory-secrets
              key: JWT_SECRET_KEY
        - name: API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: medical-inventory-secrets
              key: API_SECRET_KEY
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            nvidia.com/gpu: 1
          limits:
            memory: "8Gi"
            cpu: "4000m"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: models-volume
          mountPath: /app/models
          readOnly: true
        - name: logs-volume
          mountPath: /app/logs
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: logs-pvc
      - name: tmp-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gpu-service
  namespace: medical-inventory
  labels:
    app.kubernetes.io/name: api-gpu
    app.kubernetes.io/component: backend-gpu
    app.kubernetes.io/part-of: medical-inventory
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: api-gpu
    app.kubernetes.io/component: backend-gpu
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gpu-hpa
  namespace: medical-inventory
  labels:
    app.kubernetes.io/name: api-gpu
    app.kubernetes.io/component: backend-gpu
    app.kubernetes.io/part-of: medical-inventory
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gpu
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 25
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 180
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 120